### ISSUE TITLE
Failed to index com.github.javaparser.ast.body.(ClassOrInterfaceDeclaration|MethodDeclaration) if quarkus-poi is present

### ISSUE THREAD

**Issue by mschorsch** [quarkiverse/quarkus-poi#104]
If quarkus-poi is present as a dependency, you will receive the following message:

```
Failed to index com.github.javaparser.ast.body.ClassOrInterfaceDeclaration: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for code-with-quarkus-1.0.0-SNAPSHOT@caa5298
Failed to index com.github.javaparser.ast.body.MethodDeclaration: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for code-with-quarkus-1.0.0-SNAPSHOT@caa5298
```

Reproducer
1. Download [reproducer.zip](https://github.com/quarkiverse/quarkus-poi/files/15061506/reproducer.zip)
2. `./gradlew clean build --rerun-tasks`

Is that problematic?

**Comment by melloware** [comment]
This looks like a Jandex issue is there any more in the stack trace?

**Comment by melloware** [comment]
actually maybe a Gradle Kotlin isssue?  I only use Maven with Quarkus and have not seeing this issue it is very strange!

**Comment by melloware** [comment]
OK its just this class is the weird one `com.github.javaparser.ast.body` not sure if that is used by Quarkus or Gradle.

**Comment by gastaldi** [comment]
It looks like Gradle is using this library and leaking this into the Quarkus classloader.  

Adding a dependency on 
```gradle
    implementation("com.github.javaparser:javaparser-core")
```

makes the problem go away

**Comment by gastaldi** [comment]
This could be a bug in the Quarkus Gradle Plugin though. Have you seen this @aloubyansky ?

**Comment by melloware** [comment]
Is this still an issue @mschorsch with Quarkus 3.16.0?

**Comment by melloware** [comment]
@all-contributors add @mschorsch for bug

**Comment by mschorsch** [comment]
@melloware I think it's not an issue anymore. Thanks for adding me as a contributor 👍

**Comment by melloware** [comment]
Nice thanks for responding @mschorsch !
