### ISSUE TITLE
Page pointed to by guide link does not exist

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-poi#12]
I notice that the quarkus extension yaml points to https://quarkiverse.github.io/quarkiverse-docs/poi/dev/ as the guides link, but that page doesn't exist. That's causing a dead link on https://quarkus.io/extensions (the quarkus-poi page isn't live, because we block publication if there's a dead link). 

Could we please either 

- Add this extension to Antora in the quarkiverse docs repo (https://github.com/quarkiverse/quarkiverse-docs/commit/32b93f355eb3218abe50a6b829604780c026c6cb has an example of how to do it) 
- Switch the link in the extension yaml to point to this repository's readme, and do a new release

I'd do it, but I don't know which is best for this extension.

**Comment by holly-cummins** [comment]
Oh, and welcome to the quarkiverse!

**Comment by gastaldi** [comment]
Ah I don't believe I forgot to check that before releasing. I'll fix it right away. Thanks!
