### ISSUE TITLE
Quarkus 3 Upgrade

### ISSUE THREAD

**Issue by tpodg** [quarkiverse/quarkus-poi#17]
Should this be tested / released as alpha with Quarkus 3?
I believe this is a precondition to do some work on https://github.com/quarkiverse/quarkus-tika/issues/79

At first sight it seems to be working with minimal changes:
https://github.com/tpodg/quarkus-poi/commit/2b3a812b426f520a38a94197316aa2d8adaac2b3

**Comment by gastaldi** [comment]
The integration tests are not published in central, so I'd say that it works in Quarkus 3. Let's wait until 3.0.0.Final is released to update

**Comment by gastaldi** [comment]
Actually, I think we can update to Quarkus 3.0.0.Alpha4 with your commit and release a 2.0.0.Alpha1, WDYT?

**Comment by tpodg** [comment]
Sounds good. A new branch is probably required though?

**Comment by gastaldi** [comment]
Yeah, instructions are here: https://github.com/quarkiverse/quarkiverse/wiki/Migrating-to-Quarkus-3.x#implement-the-migration

**Comment by tpodg** [comment]
Thank you for the link. I can prepare everything described, except for the branch in this extension repo due to permissions.

**Comment by gastaldi** [comment]
@tpodg not a problem, I added you as a committer in https://github.com/quarkiverse/quarkiverse-devops/commit/cb86529cc934d1f55670fbe125bb7d3037841fb0

**Comment by gastaldi** [comment]
@all-contributors add @tpodg for code and maintenance

**Comment by tpodg** [comment]
Thank you
