### ISSUE TITLE
NoSuchMethodException: org.apache.logging.log4j.message.ReusableMessageFactory

### ISSUE THREAD

**Issue by argenstijn** [quarkiverse/quarkus-poi#28]
When you have a sheet and you enable the following:

  wb.getCreationHelper().createFormulaEvaluator().evaluateAll();

Then you will get a the following error:

` "exception": {
                        "refId": 3,
                        "exceptionType": "java.lang.NoSuchMethodException",
                        "message": "org.apache.logging.log4j.message.ReusableMessageFactory.<init>()",
                        "frames": [
                            {
                                "class": "java.lang.Class",
                                "method": "getConstructor0",
                                "line": 3585
                            },
                            {
                                "class": "java.lang.Class",
                                "method": "newInstance",
                                "line": 626
                            },
                            {
                                "class": "org.apache.logging.log4j.spi.AbstractLogger",
                                "method": "createDefaultMessageFactory",
                                "line": 228
                            },
                            {
                                "class": "org.apache.logging.log4j.spi.AbstractLogger",
                                "method": "<init>",
                                "line": 143
                            },
                            {
                                "class": "org.jboss.logmanager.log4j.JBossLogger",
                                "method": "<init>",
                                "line": 48
                            },
                            {
                                "class": "org.jboss.logmanager.log4j.JBossLoggerContext",
                                "method": "getLogger",
                                "line": 72
                            },
                            {
                                "class": "org.jboss.logmanager.log4j.JBossLoggerContext",
                                "method": "getLogger",
                                "line": 62
                            },
                            {
                                "class": "org.apache.logging.log4j.LogManager",
                                "method": "getLogger",
                                "line": 666
                            },
                            {
                                "class": "org.apache.poi.ss.formula.WorkbookEvaluator",
                                "method": "<init>",
                                "line": 81
                            },
                            {
                                "class": "org.apache.poi.ss.formula.WorkbookEvaluator",
                                "method": "<init>",
                                "line": 89
                            },
                            {
                                "class": "org.apache.poi.xssf.usermodel.XSSFFormulaEvaluator",
                                "method": "<init>",
                                "line": 41
                            },
                            {
                                "class": "org.apache.poi.xssf.usermodel.XSSFFormulaEvaluator",
                                "method": "<init>",
                                "line": 38
                            },
                            {
                                "class": "org.apache.poi.xssf.usermodel.XSSFCreationHelper",
                                "method": "createFormulaEvaluator",
                                "line": 84
                            },
                            {
                                "class": "org.apache.poi.xssf.usermodel.XSSFCreationHelper",
                                "method": "createFormulaEvaluator",
                                "line": 32
                            },`

I think the fix is something like this for me. But could you also support this in your plugin?
```
[
  {
    "name": "org.apache.logging.log4j.message.ReusableMessageFactory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "org.apache.logging.log4j.message.DefaultFlowMessageFactory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  }
]
```

Seems like the same issue : https://github.com/quarkusio/quarkus/issues/13575

**Comment by gastaldi** [comment]
@argenstijn thanks for the issue! I created https://github.com/quarkiverse/quarkus-poi/pull/29 to fix that and I'll trigger a release once you confirm that works for you.

**Comment by argenstijn** [comment]
it works :)

**Comment by gastaldi** [comment]
@argenstijn awesome! I'm cutting a 1.0.3 release now with this fix. Are you using the 2.x Alpha version too?

**Comment by argenstijn** [comment]
No, i was only using version 1.0.2. 

What are the changes in 2.X?

**Comment by gastaldi** [comment]
It is compatible with Quarkus 3, but I'll wait a bit before releasing anither Alpha
