### ISSUE TITLE
Dev UI: Add Card

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-poi#35]
I am working on adding new Dev UI card for this library which I think will be a common pattern for a lot of libraries.  I like to know which version without digging through POM files of the library itself not the extension is loaded.

![image](https://user-images.githubusercontent.com/4399574/224496712-cdda3f1a-1c9f-434c-a007-7780d897a174.png)

**Comment by gastaldi** [comment]
That's a good idea,  +1

**Comment by melloware** [comment]
PR coming!

**Comment by melloware** [comment]
I have Phillip working on an enhancement so we can add logos but this is my final ouput.
https://user-images.githubusercontent.com/4399574/224509572-0e8e2d12-eb12-45b6-bf67-2a3f866e14d9.png
