### ISSUE TITLE
POI Logo on Docs?

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-poi#66]
Question:  How did POI get its logo in the Docs site: https://quarkus.io/extensions/

![image](https://github.com/quarkiverse/quarkus-poi/assets/4399574/e6805fd3-648a-47e5-ab41-70281ab840da)

I would like to update my extensions to also have their logos?

**Comment by gastaldi** [comment]
https://github.com/quarkiverse/quarkus-poi/blob/main/runtime/src/main/resources/META-INF/quarkus-extension.yaml#L17

**Comment by melloware** [comment]
You rock!
