### ISSUE TITLE
mvn -Pnative  native:compile 编译报错

### ISSUE THREAD

**Issue by kungoudemahou** [quarkiverse/quarkus-poi#81]
不引入**quarkus-poi**可以正常编译**mvn -Pnative  native:compile**
引入后编译不通过
这是我的错误信息
![1697101319479](https://github.com/quarkiverse/quarkus-poi/assets/44722457/e924639d-18c5-4dc6-9713-572d7bcbdd0c)
这是我的pom文件
![1697102086662](https://github.com/quarkiverse/quarkus-poi/assets/44722457/59549e00-dbbd-40bf-be62-3a288887363a)
![1697102048727](https://github.com/quarkiverse/quarkus-poi/assets/44722457/c29c988f-06da-4b19-a9e1-a2cfd05f4d46)

**Comment by melloware** [comment]
It looks like you are trying to mix and match Spring Boot and Quarkus.  Quarkus POI is for Quarkus only and I don't think will work with Spring Boot.
