### ISSUE TITLE
Move `poi-scratchpad` to a different extension

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkus-poi#9]
Depending on the size, it would be interesting to have the dependency on `poi-scratchpad` in a different extension

_Originally posted by @gsmet in https://github.com/quarkiverse/quarkus-poi/pull/5#discussion_r1096540921_

**Comment by tpodg** [comment]
I just made a comparison:
- Build on M1 Apple Silicon
- Build with scratchpad included vs reverted commits (scratchpad excluded)
- Compared size of quarkus-app folder (integration tests app)
- Compared size of native binary (integration tests runner)

JVM version is 42,1 Mb vs 40,2 Mb and difference in binary size is 96,1 Mb vs 90,1 Mb. 

According to dependency tree, there should not be any additional transitive dependencies brought in with scratchpad.

**Comment by gastaldi** [comment]
Doesn't sound like it's worth changing it. I'm closing this issue. Let's revisit later if necessary
